### ISSUE TITLE
When loading a big dataset with tasks, output String builder is exploding 

### ISSUE THREAD

**Issue by bogdan-xplode** [datathings/greycat#7]
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at greycat.internal.task.CoreTaskContext.append(CoreTaskContext.java:662)
	at greycat.internal.task.CF_ForEach$1.on(CF_ForEach.java:55)
	at greycat.internal.task.CF_ForEach$1.on(CF_ForEach.java:48)
	at greycat.internal.task.CoreTaskContext.endTask(CoreTaskContext.java:471)
	at greycat.internal.task.CoreTaskContext.continueTask(CoreTaskContext.java:382)
	at playmobel.Loader$3.eval(Loader.java:140)
	at greycat.internal.task.CF_ThenDo.eval(CF_ThenDo.java:38)
	at greycat.internal.task.CoreTaskContext.continueTask(CoreTaskContext.java:396)
	at greycat.internal.task.ActionSave$1.on(ActionSave.java:31)
	at greycat.internal.task.ActionSave$1.on(ActionSave.java:28)
	at greycat.internal.heap.HeapChunkSpace$3.on(HeapChunkSpace.java:416)
	at greycat.internal.heap.HeapChunkSpace$3.on(HeapChunkSpace.java:410)
	at greycat.leveldb.LevelDBStorage.put(LevelDBStorage.java:102)
	at greycat.internal.heap.HeapChunkSpace.save(HeapChunkSpace.java:410)
	at greycat.internal.CoreGraph.save(CoreGraph.java:272)
	at greycat.internal.task.ActionSave.eval(ActionSave.java:28)
	at greycat.internal.task.CoreTaskContext.continueTask(CoreTaskContext.java:396)
	at greycat.internal.task.CF_ForEach$1.on(CF_ForEach.java:67)
	at greycat.internal.task.CF_ForEach$1.on(CF_ForEach.java:48)
	at greycat.internal.task.CoreTaskContext.endTask(CoreTaskContext.java:471)
	at greycat.internal.task.CoreTaskContext.continueTask(CoreTaskContext.java:382)
	at greycat.internal.task.CF_ForEach$1.on(CF_ForEach.java:67)
	at greycat.internal.task.CF_ForEach$1.on(CF_ForEach.java:48)
	at greycat.internal.task.CoreTaskContext.endTask(CoreTaskContext.java:471)
	at greycat.internal.task.CoreTaskContext.continueTask(CoreTaskContext.java:382)
	at playmobel.Loader$4.eval(Loader.java:119)
	at greycat.internal.task.CF_ThenDo.eval(CF_ThenDo.java:38)

**Comment by bogdan-xplode** [comment]
Basically it's from appending lots of print action, so if I use the log it is not a problem
