### ISSUE TITLE
RocksDBStorage does not work on Windows

### ISSUE THREAD

**Issue by bluezio** [datathings/greycat#94]
We are using Greycat on top of the RocksDB storage layer in our Hawk project, and our tests pass fine from Linux. However, from Windows, all we see is an error saying that the Snappy compression has not been linked in:

```
org.rocksdb.RocksDBException: Compression type Snappy is not linked with the binary.
	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:231)
	at greycat.rocksdb.RocksDBStorage.connect(RocksDBStorage.java:273)
	at greycat.internal.CoreGraph.connect(CoreGraph.java:357)
	at org.hawk.greycat.GreycatDatabase.connect(GreycatDatabase.java:539)
	at org.hawk.greycat.GreycatDatabase.reconnect(GreycatDatabase.java:508)
	at org.hawk.greycat.GreycatDatabase.run(GreycatDatabase.java:200)
	at org.hawk.integration.tests.ModelIndexingTest.setup(ModelIndexingTest.java:139)
	at org.hawk.integration.tests.ModelIndexingTest$GraphChangeListenerRule.before(ModelIndexingTest.java:95)
```

We understand this is due from the way the `rocksdbjni` library is packaged.

We have tried creating a copy of RocksDBStorage which does not use any compression, and that seems to work fine from Windows. We would rather not have a straight copy of the class, however: would it be possible to allow users of this storage engine to change the default options used to connect to RocksDB, such as the compression type? The RocksDB authors also recommend using LZ4 instead of Snappy when possible, so other people besides Windows users may benefit from this extra bit of flexibility.

Alternatively, could you make the fields in that class protected or extract the creation of the options to a protected method, so we may override them in a subclass?

Thanks for your help!

**Comment by bluezio** [comment]
Thanks, this would work for us!
